#include <algorithm>
#include <iostream>
#include <set>
#include <string>
#include <vector>
#include "datamanipulation.h"
#include "generatepositions.h"
#include "position.h"
#include "selectivity.h"
#include "statistics.h"
